name: CI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            override: true
            components: rust-src, rustfmt, clippy, rustc-dev, llvm-tools-preview
      - name: Check formatting
        run: cargo fmt --check
      - name: Apply lints
        run: cargo clippy -- -D warnings -A clippy::type-complexity -A clippy::single-match -A clippy::too_many_arguments
      - name: Build
        run: cargo build --release
      - name: Build deps
        run: cargo build --manifest-path deps_crate/Cargo.toml
      - name: Run Cargo tests
        run: cargo test --release --lib
      - name: Run dataflow analysis tests
        run: ./scripts/test_dataflow.sh
      - name: Run tests (example)
        run: ./scripts/test_examples.sh
      - name: Run tests (example-goblint)
        run: GOBLINT=yes ./scripts/test_examples.sh
      - name: Run tests (benchmark-success)
        run: ./scripts/test_bench_success.sh
      - name: Run tests (benchmark-fail)
        run: ./scripts/test_bench_fail.sh
      - name: Run tests (benchmark-goblint-success)
        run: ./scripts/test_bench_goblint_success.sh
      - name: Run tests (benchmark-goblint-fail)
        run: ./scripts/test_bench_goblint_fail.sh
